const portfolioData = {
    es: {
        name: "Jean Esteve",
        title: "Data & Prompt Engineer | Product Management",
        nav_about: "Acerca de",
        nav_experience: "Experiencia",
        nav_projects: "Proyectos",
        nav_skills: "Habilidades",
        status_available: "Disponible",
        hero_text: "Prompt Engineer y desarrollador enfocado en automatización de procesos y estructuración de datos. Me especializo en orquestar modelos de IA generativa y diseñar arquitecturas RAG para resolver cuellos de botella operativos. Mi enfoque combina rigor técnico en Python con metodologías de Product Management para construir sistemas precisos, medibles y alineados con objetivos de negocio.",
        exp_title: "Experiencia",
        exp_1_role: "Técnico de Soporte Freelance",
        exp_1_company: "Servicios Técnicos de PC",
        exp_1_date: "2021 – 2025",
        exp_1_desc: "Diagnóstico y resolución de incidencias técnicas en hardware y software. Consultoría técnica personalizada y levantamiento de requerimientos.",
        exp_1_tag_1: "Hardware",
        exp_1_tag_2: "Soporte L1/L2",
        exp_1_tag_3: "CX",
        exp_2_role: "Soldado de Soporte Técnico",
        exp_2_company: "Ejército Argentino",
        exp_2_date: "2022 – 2023",
        exp_2_desc: "Asistencia técnica presencial y remota al personal interno. Participación en el diseño y ensamblaje de un simulador virtual de tanques, redactando la documentación técnica.",
        exp_2_tag_1: "Redes",
        exp_2_tag_2: "Soporte Crítico",
        exp_2_tag_3: "Documentación",
        proj_title: "Proyectos",
        proj_1_title: "Motor de Extracción Documental B2B",
        proj_1_desc: "Pipeline asíncrono para digitalización y estructuración de documentos legales y financieros complejos. Utiliza Vision-Language Models para procesar escaneos ruidosos. Implementa validación estricta de formato (JSON schema compliance) e iteración de prompts para optimizar la fidelidad del texto.",
        proj_1_tag_1: "Python",
        proj_1_tag_2: "VLMs",
        proj_1_tag_3: "OCR",
        proj_1_tag_4: "JSON",
        proj_2_title: "Primero Los Hechos (PLH) - Fact-Checking",
        proj_2_desc: "Plataforma de auditoría fáctica. Diseñada con arquitecturas de verificación multi-paso utilizando LLMs de frontera. Integra técnicas avanzadas (CoT, ReAct) y cruce de datos para mitigar alucinaciones.",
        proj_2_tag_1: "RAG",
        proj_2_tag_2: "Prompt Engineering",
        proj_2_tag_3: "Scraping",
        proj_2_tag_4: "SQL",
        skills_title: "Habilidades",
        skill_cat_1: "IA & Datos",
        skill_1_1: "Prompt Engineering",
        skill_1_2: "RAG",
        skill_1_3: "LLMs",
        skill_1_4: "VLMs",
        skill_1_5: "Python",
        skill_1_6: "SQL",
        skill_cat_2: "Metodologías & Procesos",
        skill_2_1: "Product Management",
        skill_2_2: "Automatización",
        skill_2_3: "ETL",
        skill_2_4: "Scraping",
        skill_2_5: "Documentación",
        skill_cat_3: "Soporte & IT",
        skill_3_1: "Hardware",
        skill_3_2: "Redes",
        skill_3_3: "Soporte L1/L2",
        skill_3_4: "Sistemas Operativos",
        cta_title: "¿Hablamos? Estoy abierto a nuevas oportunidades.",
        github: "GitHub",
        linkedin: "LinkedIn",
        email: "Email"
    },
    en: {
        name: "Jean Esteve",
        title: "Data & Prompt Engineer | Product Management",
        nav_about: "About",
        nav_experience: "Experience",
        nav_projects: "Projects",
        nav_skills: "Skills",
        status_available: "Available for work",
        hero_text: "Prompt Engineer and developer focused on process automation and data structuring. I specialize in orchestrating generative AI models and designing RAG architectures to resolve operational bottlenecks. My approach combines technical rigor in Python with Product Management methodologies to build precise, measurable systems aligned with business objectives.",
        exp_title: "Experience",
        exp_1_role: "Freelance Technical Support",
        exp_1_company: "PC Technical Services",
        exp_1_date: "2021 – 2025",
        exp_1_desc: "Diagnosis and resolution of hardware and software technical incidents. Personalized technical consulting and requirements gathering.",
        exp_1_tag_1: "Hardware",
        exp_1_tag_2: "L1/L2 Support",
        exp_1_tag_3: "CX",
        exp_2_role: "Technical Support Soldier",
        exp_2_company: "Argentine Army",
        exp_2_date: "2022 – 2023",
        exp_2_desc: "On-site and remote technical assistance for internal personnel. Participation in the design and assembly of a virtual tank simulator, including writing the technical documentation.",
        exp_2_tag_1: "Networks",
        exp_2_tag_2: "Critical Support",
        exp_2_tag_3: "Documentation",
        proj_title: "Projects",
        proj_1_title: "B2B Document Extraction Engine",
        proj_1_desc: "Asynchronous pipeline for the digitization and structuring of complex legal and financial documents. Uses Vision-Language Models to process noisy scans. Implements strict format validation (JSON schema compliance) and prompt iteration to optimize text fidelity.",
        proj_1_tag_1: "Python",
        proj_1_tag_2: "VLMs",
        proj_1_tag_3: "OCR",
        proj_1_tag_4: "JSON",
        proj_2_title: "Primero Los Hechos (PLH) - Fact-Checking",
        proj_2_desc: "Fact-auditing platform. Designed with multi-step verification architectures using frontier LLMs. Integrates advanced techniques (CoT, ReAct) and data cross-referencing to mitigate hallucinations.",
        proj_2_tag_1: "RAG",
        proj_2_tag_2: "Prompt Engineering",
        proj_2_tag_3: "Scraping",
        proj_2_tag_4: "SQL",
        skills_title: "Skills",
        skill_cat_1: "AI & Data",
        skill_1_1: "Prompt Engineering",
        skill_1_2: "RAG",
        skill_1_3: "LLMs",
        skill_1_4: "VLMs",
        skill_1_5: "Python",
        skill_1_6: "SQL",
        skill_cat_2: "Methodologies & Processes",
        skill_2_1: "Product Management",
        skill_2_2: "Automation",
        skill_2_3: "ETL",
        skill_2_4: "Scraping",
        skill_2_5: "Documentation",
        skill_cat_3: "IT & Support",
        skill_3_1: "Hardware",
        skill_3_2: "Networking",
        skill_3_3: "L1/L2 Support",
        skill_3_4: "Operating Systems",
        cta_title: "Let's talk? I'm open to new opportunities.",
        github: "GitHub",
        linkedin: "LinkedIn",
        email: "Email"
    }
};

// Exporting to make it globally available if used as a module, or just accessible by index.html script
window.portfolioData = portfolioData;
